# permissions for end users to edit ecssnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ecssnapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cloudoperator
    app.kubernetes.io/part-of: cloudoperator
    app.kubernetes.io/managed-by: kustomize
  name: ecssnapshot-editor-role
rules:
- apiGroups:
  - aliyun.ecs.doslab.io
  resources:
  - ecssnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aliyun.ecs.doslab.io
  resources:
  - ecssnapshots/status
  verbs:
  - get
